databases:
  - name: postgres
    ipAllowList: []

services:
  - type: web
    name: rails  
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: RAILS_MASTER_KEY
        value: "76438892726262cb614bc90a8a5d990d"
        sync: false
      - key: DATABASE_URL
        value: ""
        fromDasebase: 
          name: postgres
          property: connectionString
  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction